name: DevHub API CD

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20.x'
      docker-image-name:
        required: true
        type: string
      dockerhub-username:
        required: true
        type: string
      dockerhub-token:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy DevHub API
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Git info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          git log -1 --oneline

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: List installed packages
        run: npm list --depth=0

      - name: Build Docker image
        run: docker build -t ${{ inputs.docker-image-name }} . | tee docker-build.log

      - name: Show Docker images
        run: docker images

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ inputs.dockerhub-token }}

      - name: Push Docker image
        run: docker push ${{ inputs.docker-image-name }} | tee docker-push.log

      - name: Show pushed image info
        run: |
            echo "Pushed image: ${{ inputs.docker-image-name }}"

      - name: Deploy (placeholder)
        run: echo "Deploy step here (e.g., SSH, cloud CLI, etc.)" | tee deploy.log

      - name: Workflow Results Summary
        if: always()
        run: |
          echo "## DevHub API CD Results" >> $GITHUB_STEP_SUMMARY
          echo "### Docker Build Log" >> $GITHUB_STEP_SUMMARY
          cat docker-build.log >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No Docker build log found." >> $GITHUB_STEP_SUMMARY
          echo "### Docker Push Log" >> $GITHUB_STEP_SUMMARY
          cat docker-push.log >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No Docker push log found." >> $GITHUB_STEP_SUMMARY
          echo "### Deploy Log" >> $GITHUB_STEP_SUMMARY
          cat deploy.log >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No deploy log found." >> $GITHUB_STEP_SUMMARY
