name: DevHub Portal CI

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20.x'

jobs:
  ci:
    name: CI DevHub Portal
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Show Git info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          git log -1 --oneline

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies and Run Lint, Tests.
        run: |
          npm install
          npm list --depth=0
          npm run lint
          cat ./lint.log || echo "No lint log found."
          npm test
          cat ./test-results.log || echo "No test results log found."

      - name: Build 
        run: |
          npm run build
          ls -lh dist/ || echo "No dist folder found."

      - name: Workflow Results Summary
        if: always()
        run: |
          echo "## DevHub Portal CI Results" >> $GITHUB_STEP_SUMMARY
          echo "### Lint Results" >> $GITHUB_STEP_SUMMARY
          cat lint.log >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No lint log found." >> $GITHUB_STEP_SUMMARY
          echo "### Test Results" >> $GITHUB_STEP_SUMMARY
          cat test-results.log >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No test results log found." >> $GITHUB_STEP_SUMMARY
          echo "### Build Output" >> $GITHUB_STEP_SUMMARY
          ls -lh dist/ >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "No dist folder found." >> $GITHUB_STEP_SUMMARY
